language: elixir
elixir:
  - 1.8
otp_release:
  - 21.0
addons:
  postgresql: '9.4'
services:
  - postgresql
cache:
  directories:
    - _build
    - deps
    - priv/plts
env:
  - MIX_ENV=test
before_script:
  - mix ecto.create && mix ecto.migrate
script:
  - mix test
  - mix coveralls.travis
  - mix dialyzer